[project]
dependencies = [
  "fvcore==0.1.5.post20221221",
  "gdown==4.7.1",
  "matplotlib==3.8.2",
  "nibabel==5.1.0",
  "onnx-tf==1.10.0",
  "pandas==2.1.3",
  "scikit-image==0.20.0",
  "segmentation-models-pytorch==0.3.3",
  "tensorflow-probability==0.19.0",
  "tensorflowjs==4.4.0"
]
name = "UNKNOWN"
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "coverage==7.3.2",
  "djlint==1.34.1",
  "mypy==1.7.1",
  "ruff==0.1.6",
  "ssort==0.11.6",
  "toml-sort==0.23.1"
]
