[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"fvcore==0.1.5.post20221221",
	"gdown==4.7.1",
	"matplotlib==3.7.1",
	"nibabel==5.1.0",
	"onnx-tf==1.10.0",
	"pandas==2.0.1",
	"scikit-image==0.20.0",
	"segmentation-models-pytorch==0.3.2",
	"tensorflow-probability==0.19.0",
	"tensorflowjs==4.4.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.2.0",
	"ruff==0.0.267",
]
