on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Test
        run: |
          make -C python/
          make
